In [14]:
import numpy as np
import scipy.linalg as lg
import scipy.fftpack as fp

np.set_printoptions(precision=3, suppress=True)
π= np.pi
π

3.141592653589793

In [15]:
x= np.array([1,1,1,1])
X= fp.fft(x)
xx= fp.ifft(X)
x, X, xx

(array([1, 1, 1, 1]),
 array([4.000-0.000j, 0.000+0.000j, 0.000-0.000j, 0.000-0.000j]),
 array([1.000+0.000j, 1.000+0.000j, 1.000-0.000j, 1.000+0.000j]))

In [18]:
N=4
n= np.arange(N).reshape(-1,1)
k= np.arange(N).reshape(1,-1)
dftMat= np.exp(-1j*2*π/N*n@k)
dftMat

array([[ 1.000+0.000j,  1.000+0.000j,  1.000+0.000j,  1.000+0.000j],
       [ 1.000+0.000j,  0.000-1.000j, -1.000-0.000j, -0.000+1.000j],
       [ 1.000+0.000j, -1.000-0.000j,  1.000+0.000j, -1.000-0.000j],
       [ 1.000+0.000j, -0.000+1.000j, -1.000-0.000j,  0.000-1.000j]])

In [20]:
X= x@dftMat
X

array([ 4.000+0.000j, -0.000-0.000j,  0.000-0.000j,  0.000-0.000j])

In [21]:
idftMat= lg.inv(dftMat)
idftMat

array([[ 0.250+0.000j,  0.250+0.000j,  0.250-0.000j,  0.250-0.000j],
       [ 0.250-0.000j,  0.000+0.250j, -0.250+0.000j, -0.000-0.250j],
       [ 0.250-0.000j, -0.250+0.000j,  0.250-0.000j, -0.250+0.000j],
       [ 0.250-0.000j, -0.000-0.250j, -0.250+0.000j,  0.000+0.250j]])

In [22]:
xx= X@idftMat
xx

array([1.000+0.000j, 1.000-0.000j, 1.000-0.000j, 1.000-0.000j])

In [25]:
idftMat2= dftMat.T.conj() /N
idftMat2

array([[ 0.250-0.000j,  0.250-0.000j,  0.250-0.000j,  0.250-0.000j],
       [ 0.250-0.000j,  0.000+0.250j, -0.250+0.000j, -0.000-0.250j],
       [ 0.250-0.000j, -0.250+0.000j,  0.250-0.000j, -0.250+0.000j],
       [ 0.250-0.000j, -0.000-0.250j, -0.250+0.000j,  0.000+0.250j]])

In [26]:
xx2= X@idftMat2
xx2

array([1.000-0.000j, 1.000-0.000j, 1.000+0.000j, 1.000+0.000j])

In [29]:
np.isclose(idftMat, idftMat2)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [34]:
dftMat.conj().transpose() @ dftMat

array([[ 4.000+0.000j, -0.000-0.000j,  0.000-0.000j,  0.000-0.000j],
       [-0.000+0.000j,  4.000+0.000j, -0.000-0.000j,  0.000-0.000j],
       [ 0.000+0.000j, -0.000+0.000j,  4.000+0.000j, -0.000-0.000j],
       [ 0.000+0.000j,  0.000+0.000j, -0.000+0.000j,  4.000+0.000j]])

In [ ]:
np.eye(4)

array([[1.000, 0.000, 0.000, 0.000],
       [0.000, 1.000, 0.000, 0.000],
       [0.000, 0.000, 1.000, 0.000],
       [0.000, 0.000, 0.000, 1.000]])

In [44]:
dftMat[1,:].conj() @ dftMat[:,3].T

-2.449293598294707e-16j

In [49]:
N=4
W= np.random.random([N,N]) + 1j* np.random.random([N,N]) 
W

array([[0.685+0.983j, 0.160+0.792j, 0.178+0.022j, 0.286+0.031j],
       [0.755+0.611j, 0.864+0.812j, 0.411+0.986j, 0.029+0.591j],
       [0.123+0.678j, 0.985+0.327j, 0.823+0.475j, 0.283+0.036j],
       [0.855+0.810j, 0.128+0.636j, 0.699+0.342j, 0.237+0.200j]])

In [50]:
iW= lg.inv(W)
iW

array([[ 0.109-0.669j,  0.090-0.106j, -0.568-0.160j,  0.515+0.425j],
       [ 0.442+0.123j,  0.554+0.118j,  0.513-0.278j, -1.216-0.322j],
       [-1.380+0.583j, -0.365+0.452j,  0.612-0.103j,  1.442-0.855j],
       [ 1.877-0.531j, -0.503-1.853j, -0.512+1.143j, -0.809+1.272j]])

In [51]:
W@iW

array([[ 1.000-0.000j, -0.000+0.000j,  0.000+0.000j,  0.000+0.000j],
       [-0.000+0.000j,  1.000+0.000j,  0.000+0.000j,  0.000-0.000j],
       [-0.000-0.000j, -0.000+0.000j,  1.000+0.000j,  0.000-0.000j],
       [-0.000-0.000j, -0.000+0.000j,  0.000+0.000j,  1.000-0.000j]])

In [68]:

N=1024
W= np.random.random([N,N]) + 1j* np.random.random([N,N]) 
%timeit iW= lg.inv(W)
#W, iW, W@iW #, np.allclose(W@iW, np.eye(N))

89.2 ms ± 520 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [69]:

N=1024
W= np.random.random([N,N]) + 1j* np.random.random([N,N]) 
%timeit tW= W.transpose().conj()

5.94 ms ± 60.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [71]:
N= 1024
n= np.arange(N).reshape(-1,1)
k= np.arange(N).reshape(1,-1)
dftMat= np.exp(-1j*2*π/N*n@k)

In [79]:
%timeit dftMat_inv= lg.inv(dftMat)
# 91.4 ms ± 4.55 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

89.6 ms ± 562 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [80]:
%timeit dftMat_transconj= dftMat.T.conj()
# 5.93 ms ± 31.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


5.98 ms ± 35.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [81]:
91.4/5.93 # == 15.41
# when N=1024, .inv() / .T.conj() = 15 times slower

15.413153456998316

In [83]:
# DFT (N-point)
# DCT- type1 (M+1) point
# where M= N/2
# and input to DFT is appended to be even-symmetric
# x8points= [1,2,3,4,5,4,3,2]
# x5points= [1,2,3,4,5]
# DCT(x5points)[k] == DFT(x8points)[k], for k in [0,1,2,3,4]

x8points= np.array([1,2,3,4,5,4,3,2])
x5points= np.array([1,2,3,4,5])

fp.fft(x8points), fp.dct(x5points, type=1)

(array([24.000-0.000j, -6.828+0.000j,  0.000-0.000j, -1.172+0.000j,
         0.000-0.000j, -1.172-0.000j,  0.000+0.000j, -6.828-0.000j]),
 array([24.000, -6.828,  0.000, -1.172,  0.000]))

In [ ]:
# cosMat vs dftMat
N=8
n= np.arange(N).reshape(-1,1)
k= np.arange(N).reshape(1,-1)
dftMat= np.exp(-1j*2*π/N*n@k)
dftMat

In [102]:
M=N//2

n= np.arange(M+1).reshape(-1,1)
k= np.arange(M+1).reshape(1,-1)

cosMat1= np.cos(π/M*n@k)
cosMat1.T @ cosMat1

array([[ 5.000,  0.000,  1.000,  0.000,  1.000],
       [ 0.000,  3.000,  0.000,  1.000, -0.000],
       [ 1.000,  0.000,  3.000,  0.000,  1.000],
       [ 0.000,  1.000,  0.000,  3.000, -0.000],
       [ 1.000, -0.000,  1.000, -0.000,  5.000]])

In [105]:
cosMat4= np.cos(π/(M+1)*(n+1/2)@(k+1/2))
cosMat4.T @ cosMat4

array([[ 2.500,  0.000,  0.000, -0.000, -0.000],
       [ 0.000,  2.500, -0.000,  0.000,  0.000],
       [ 0.000, -0.000,  2.500, -0.000, -0.000],
       [-0.000,  0.000, -0.000,  2.500, -0.000],
       [-0.000,  0.000, -0.000, -0.000,  2.500]])

In [106]:
cosMat2= np.cos(π/(M+1)*(n+1/2)@(k))
cosMat2.T @ cosMat2

array([[ 5.000,  0.000, -0.000,  0.000, -0.000],
       [ 0.000,  2.500,  0.000, -0.000,  0.000],
       [-0.000,  0.000,  2.500,  0.000, -0.000],
       [ 0.000, -0.000,  0.000,  2.500,  0.000],
       [-0.000,  0.000, -0.000,  0.000,  2.500]])

In [117]:
cosMat3= np.cos(π/(M+1)*(n)@(k+1/2))
cosMat3.T @ cosMat3

array([[3.000, 0.500, 0.500, 0.500, 0.500],
       [0.500, 3.000, 0.500, 0.500, 0.500],
       [0.500, 0.500, 3.000, 0.500, 0.500],
       [0.500, 0.500, 0.500, 3.000, 0.500],
       [0.500, 0.500, 0.500, 0.500, 3.000]])

In [121]:
fp.rfft?

In [126]:
x= np.array([1,2,3,4,5,4,3,2])
fp.fft(x), \
fp.rfft(x),\
fp.dct(x[0:4+1], type=1)

(array([24.000-0.000j, -6.828+0.000j,  0.000-0.000j, -1.172+0.000j,
         0.000-0.000j, -1.172-0.000j,  0.000+0.000j, -6.828-0.000j]),
 array([24.000, -6.828,  0.000,  0.000, -0.000, -1.172,  0.000,  0.000]),
 array([24.000, -6.828,  0.000, -1.172,  0.000]))

In [130]:
N=1024
x= np.random.random(N)

In [136]:
%timeit X_fft= fp.fft(x)

11.7 µs ± 25.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [135]:
%timeit X_rfft= fp.rfft(x)

8.54 µs ± 33.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [137]:
%timeit X_dct1= fp.dct(x[0:N//2+1], type=1)

11 µs ± 45.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
