# DFT 補充 ....

## Chapter 7  Discrete Fourier Transform

https://en.wikipedia.org/wiki/Discrete_Fourier_transform

- 正轉換 (DFT)

for $k \in [0,...., N-1]$
![](https://wikimedia.org/api/rest_v1/media/math/render/svg/18b0e4c82f095e3789e51ad8c2c6685306b5662b)

----

- 逆轉換 (inverse DFT)

for $n \in [0,...., N-1]$
![](https://wikimedia.org/api/rest_v1/media/math/render/svg/230e50dc8318b8806b7fa8e33d2662aca6816347)

----

where,
$ i = j = \sqrt{-1} $

and,

$
e^{iφ} = cos(φ) + i \cdot sin(φ) 
$

You can see the derivation at http://en.wikipedia.org/wiki/Euler's_formula.

![](https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Euler%27s_formula.svg/1280px-Euler%27s_formula.svg.png)

In [67]:
import numpy as np
import scipy.fftpack as fp

import scipy.linalg  as lg

np.set_printoptions(precision=3, suppress=True)
π= np.pi
π

3.141592653589793

In [68]:
x= np.array([1,0,0,0])
X= fp.fft(x)
xx= fp.ifft(X)
x, X, xx

(array([1, 0, 0, 0]),
 array([1.-0.j, 1.+0.j, 1.-0.j, 1.-0.j]),
 array([1.+0.j, 0.+0.j, 0.-0.j, 0.+0.j]))

In [69]:
N= x.size
n= np.arange(N).reshape(-1,1)# rows= N, cols=1
k= np.arange(N).reshape(1,-1)# 1 x N
dftMat= np.exp(-1j*2*π/N*n@k)
dftMat

array([[ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j],
       [ 1.+0.j,  0.-1.j, -1.-0.j, -0.+1.j],
       [ 1.+0.j, -1.-0.j,  1.+0.j, -1.-0.j],
       [ 1.+0.j, -0.+1.j, -1.-0.j,  0.-1.j]])

In [70]:
X= x@dftMat  # x.shape= (1,N); dftMat.shape==(N,N)
X # X.shape= (N,N)

array([1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j])

In [71]:
dftMat

array([[ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j],
       [ 1.+0.j,  0.-1.j, -1.-0.j, -0.+1.j],
       [ 1.+0.j, -1.-0.j,  1.+0.j, -1.-0.j],
       [ 1.+0.j, -0.+1.j, -1.-0.j,  0.-1.j]])

In [72]:
idftMat= lg.inv(dftMat) #np.linalg.inv(dftMat)
idftMat

array([[ 0.25+0.j  ,  0.25+0.j  ,  0.25-0.j  ,  0.25-0.j  ],
       [ 0.25-0.j  ,  0.  +0.25j, -0.25+0.j  , -0.  -0.25j],
       [ 0.25-0.j  , -0.25+0.j  ,  0.25-0.j  , -0.25+0.j  ],
       [ 0.25-0.j  , -0.  -0.25j, -0.25+0.j  ,  0.  +0.25j]])

In [73]:
%timeit idftMat= lg.inv(dftMat)
# slow

11 µs ± 122 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [74]:
%timeit idftMat= dftMat.conjugate()
# fast

609 ns ± 3.36 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [75]:
11e-6/621e-9

17.713365539452496

In [76]:
np.isclose(lg.inv(dftMat), dftMat.conjugate()/N)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [77]:
dftMat@lg.inv(dftMat)

array([[ 1.-0.j, -0.+0.j,  0.-0.j,  0.+0.j],
       [-0.+0.j,  1.-0.j,  0.-0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  1.-0.j, -0.-0.j],
       [ 0.+0.j,  0.-0.j,  0.+0.j,  1.-0.j]])

In [78]:
dftMat@dftMat.conjugate()/N

array([[ 1.+0.j, -0.+0.j,  0.+0.j,  0.+0.j],
       [-0.-0.j,  1.+0.j, -0.+0.j,  0.+0.j],
       [ 0.-0.j, -0.-0.j,  1.+0.j, -0.+0.j],
       [ 0.-0.j,  0.-0.j, -0.-0.j,  1.+0.j]])

In [79]:
idftMat2= dftMat.T.conj() /N
idftMat2

array([[ 0.25-0.j  ,  0.25-0.j  ,  0.25-0.j  ,  0.25-0.j  ],
       [ 0.25-0.j  ,  0.  +0.25j, -0.25+0.j  , -0.  -0.25j],
       [ 0.25-0.j  , -0.25+0.j  ,  0.25-0.j  , -0.25+0.j  ],
       [ 0.25-0.j  , -0.  -0.25j, -0.25+0.j  ,  0.  +0.25j]])

In [80]:
xx2= X@idftMat2
xx2

array([ 1.+0.j, -0.+0.j,  0.+0.j,  0.+0.j])

In [81]:
np.isclose(idftMat, idftMat2)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [82]:
dftMat.conj().transpose()/N \
@ dftMat

array([[ 1.+0.j, -0.-0.j,  0.-0.j,  0.-0.j],
       [-0.+0.j,  1.+0.j, -0.-0.j,  0.-0.j],
       [ 0.+0.j, -0.+0.j,  1.+0.j, -0.-0.j],
       [ 0.+0.j,  0.+0.j, -0.+0.j,  1.+0.j]])

In [83]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [84]:
dftMat[1,:].conj() @ dftMat[:,3].T

-2.449293598294707e-16j

In [85]:
N=4
W= np.random.random([N,N]) + 1j* np.random.random([N,N]) 
W

array([[0.114+0.794j, 0.949+0.588j, 0.527+0.282j, 0.889+0.864j],
       [0.772+0.577j, 0.421+0.356j, 0.873+0.844j, 0.292+0.259j],
       [0.607+0.283j, 0.455+0.529j, 0.031+0.684j, 0.029+0.911j],
       [0.646+0.454j, 0.446+0.522j, 0.579+0.761j, 0.053+0.537j]])

In [86]:
iW= lg.inv(W)
iW

array([[-0.035-0.17j ,  2.011-2.023j,  2.123-0.074j, -3.351+2.193j],
       [-0.099-1.121j, -6.211+1.845j, -3.185-0.219j,  9.575-1.474j],
       [-0.144+0.576j,  1.184+1.186j, -0.834+0.856j, -0.309-2.623j],
       [ 0.822+0.22j ,  2.574-2.974j,  2.001-1.731j, -5.065+4.521j]])

In [87]:
W@iW

array([[ 1.-0.j,  0.+0.j, -0.-0.j,  0.+0.j],
       [ 0.+0.j,  1.+0.j, -0.-0.j, -0.+0.j],
       [-0.+0.j,  0.+0.j,  1.-0.j,  0.+0.j],
       [-0.+0.j,  0.+0.j,  0.-0.j,  1.+0.j]])

In [88]:

N=1024
W= np.random.random([N,N]) + 1j* np.random.random([N,N]) 
%timeit iW= lg.inv(W)
#W, iW, W@iW #, np.allclose(W@iW, np.eye(N))

88.6 ms ± 420 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [89]:

N=1024
W= np.random.random([N,N]) + 1j* np.random.random([N,N]) 
%timeit tW= W.conj()

5.84 ms ± 54.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [90]:
N= 1024
x= np.random.random(N)

def ryDft(x):
    n= np.arange(N).reshape(-1,1)
    k= np.arange(N).reshape(1,-1)
    
    dftMat= np.exp(-1j*2*π/N*n@k)
    
    X= x @ dftMat
    
    return X



In [91]:
## %timeit X= ryDft(x)

n= np.arange(N).reshape(-1,1)
k= np.arange(N).reshape(1,-1)

dftMat= np.exp(-1j*2*π/N*n@k)

%timeit X= x @ dftMat
# 880 µs 

330 µs ± 4.56 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [92]:
%timeit X1= fp.fft(x)

11.3 µs ± 72.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [93]:
858 /22.6, (N*N) / (N*np.log(N))

(37.9646017699115, 147.73197218702984)

In [94]:
idftMat = dftMat.T.conj()/N

In [95]:
%timeit dftMat_inv= lg.inv(dftMat)
# 91.4 ms ± 4.55 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

96.4 ms ± 4.96 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [96]:
%timeit dftMat_transconj= dftMat.T.conj()
# 5.93 ms ± 31.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


5.8 ms ± 82.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [97]:
91.4/5.93 # == 15.41
# when N=1024, .inv() / .T.conj() = 15 times slower

15.413153456998316

In [98]:
# DFT (N-point)
# DCT- type1 (M+1) point
# where M= N/2
# and input to DFT is appended to be even-symmetric
# x8points= [1,2,3,4,5,4,3,2]
# x5points= [1,2,3,4,5]
# DCT(x5points)[k] == DFT(x8points)[k], for k in [0,1,2,3,4]

x8points= np.array([1,2,3,4,5,4,3,2])
x5points= np.array([1,2,3,4,5])

fp.fft(x8points), fp.dct(x5points, type=1)

(array([24.   -0.j, -6.828+0.j,  0.   -0.j, -1.172+0.j,  0.   -0.j,
        -1.172-0.j,  0.   +0.j, -6.828-0.j]),
 array([24.   , -6.828,  0.   , -1.172,  0.   ]))

In [99]:
# cosMat vs dftMat
N=8
n= np.arange(N).reshape(-1,1)
k= np.arange(N).reshape(1,-1)
dftMat= np.exp(-1j*2*π/N*n@k)
dftMat

array([[ 1.   +0.j   ,  1.   +0.j   ,  1.   +0.j   ,  1.   +0.j   ,
         1.   +0.j   ,  1.   +0.j   ,  1.   +0.j   ,  1.   +0.j   ],
       [ 1.   +0.j   ,  0.707-0.707j,  0.   -1.j   , -0.707-0.707j,
        -1.   -0.j   , -0.707+0.707j, -0.   +1.j   ,  0.707+0.707j],
       [ 1.   +0.j   ,  0.   -1.j   , -1.   -0.j   , -0.   +1.j   ,
         1.   +0.j   ,  0.   -1.j   , -1.   -0.j   , -0.   +1.j   ],
       [ 1.   +0.j   , -0.707-0.707j, -0.   +1.j   ,  0.707-0.707j,
        -1.   -0.j   ,  0.707+0.707j,  0.   -1.j   , -0.707+0.707j],
       [ 1.   +0.j   , -1.   -0.j   ,  1.   +0.j   , -1.   -0.j   ,
         1.   +0.j   , -1.   -0.j   ,  1.   +0.j   , -1.   -0.j   ],
       [ 1.   +0.j   , -0.707+0.707j,  0.   -1.j   ,  0.707+0.707j,
        -1.   -0.j   ,  0.707-0.707j, -0.   +1.j   , -0.707-0.707j],
       [ 1.   +0.j   , -0.   +1.j   , -1.   -0.j   ,  0.   -1.j   ,
         1.   +0.j   , -0.   +1.j   , -1.   -0.j   , -0.   -1.j   ],
       [ 1.   +0.j   ,  0.707+0.707j, -0.

In [100]:
M=N//2

n= np.arange(M+1).reshape(-1,1)
k= np.arange(M+1).reshape(1,-1)

cosMat1= np.cos(π/M*n@k)
cosMat1.T @ cosMat1

array([[ 5.,  0.,  1.,  0.,  1.],
       [ 0.,  3.,  0.,  1., -0.],
       [ 1.,  0.,  3.,  0.,  1.],
       [ 0.,  1.,  0.,  3., -0.],
       [ 1., -0.,  1., -0.,  5.]])

In [101]:
cosMat4= np.cos(π/(M+1)*(n+1/2)@(k+1/2))
cosMat4.T @ cosMat4

array([[ 2.5,  0. ,  0. , -0. , -0. ],
       [ 0. ,  2.5, -0. ,  0. ,  0. ],
       [ 0. , -0. ,  2.5, -0. , -0. ],
       [-0. ,  0. , -0. ,  2.5, -0. ],
       [-0. ,  0. , -0. , -0. ,  2.5]])

In [102]:
cosMat2= np.cos(π/(M+1)*(n+1/2)@(k))
cosMat2.T @ cosMat2

array([[ 5. ,  0. , -0. ,  0. , -0. ],
       [ 0. ,  2.5,  0. , -0. ,  0. ],
       [-0. ,  0. ,  2.5,  0. , -0. ],
       [ 0. , -0. ,  0. ,  2.5,  0. ],
       [-0. ,  0. , -0. ,  0. ,  2.5]])

In [103]:
cosMat3= np.cos(π/(M+1)*(n)@(k+1/2))
cosMat3.T @ cosMat3

array([[3. , 0.5, 0.5, 0.5, 0.5],
       [0.5, 3. , 0.5, 0.5, 0.5],
       [0.5, 0.5, 3. , 0.5, 0.5],
       [0.5, 0.5, 0.5, 3. , 0.5],
       [0.5, 0.5, 0.5, 0.5, 3. ]])

In [104]:
fp.rfft?

In [105]:
x= np.array([1,2,3,4,5,4,3,2])
fp.fft(x), \
fp.rfft(x),\
fp.dct(x[0:4+1], type=1)

(array([24.   -0.j, -6.828+0.j,  0.   -0.j, -1.172+0.j,  0.   -0.j,
        -1.172-0.j,  0.   +0.j, -6.828-0.j]),
 array([24.   , -6.828,  0.   ,  0.   , -0.   , -1.172,  0.   ,  0.   ]),
 array([24.   , -6.828,  0.   , -1.172,  0.   ]))

In [106]:
N=1024
x= np.random.random(N)

In [107]:
%timeit X_fft= fp.fft(x)

11.4 µs ± 59.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [108]:
%timeit X_rfft= fp.rfft(x)

8.52 µs ± 67.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [109]:
%timeit X_dct1= fp.dct(x[0:N//2+1], type=1)

10.2 µs ± 90.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [110]:
import numpy as np
import scipy.fftpack as fp

N= 1024
x= np.random.random(N) #np.ones(N)

In [111]:
X= fp.fft(x)
X

array([514.471 -0.j   ,   3.899+12.933j,  16.346 -0.63j , ...,
        -5.522 +7.603j,  16.346 +0.63j ,   3.899-12.933j])

In [112]:
π= np.pi

n= np.arange(N)
k= np.arange(N)

W= np.exp(np.outer(n,k) * (-1j*2*π/N))

In [113]:
X= x@W
X

array([514.471 +0.j   ,   3.899+12.933j,  16.346 -0.63j , ...,
        -5.522 +7.603j,  16.346 +0.63j ,   3.899-12.933j])

In [114]:
import numpy as np

π= np.pi

def ryFFT(x):
    
    N= x.size
    if N == 1:
        X= x
        return X
    
    He = ryFFT(x[0::2])
    Ho = ryFFT(x[1::2])
    
    k= np.arange(N)
    w= np.exp(-1j*2*π/N)
    
    X=   np.tile(He, 2)       \
       + np.tile(Ho, 2) * w**k
    
    return X

ryFFT(x)

array([514.471 +0.j   ,   3.899+12.933j,  16.346 -0.63j , ...,
        -5.522 +7.603j,  16.346 +0.63j ,   3.899-12.933j])

In [115]:
%timeit X= fp.fft(x)
# 11.2 µs ± 54.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

11.4 µs ± 74.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [116]:
%timeit X1= x@W
# 329 µs ± 10.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

307 µs ± 13.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [117]:
%timeit X2= ryFFT(x) 
# 14 ms ± 47.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

# 有關於速度，我們自己的 implementation 基本上還是很難與系統抗衡！！應該與 memory 的存取有關！

14.4 ms ± 55.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [118]:
# fp.fft : x@W : ryFFT
11.2, 329, 14000
1, 329/11.2, 14000/11.2

(1, 29.375000000000004, 1250.0)

In [119]:
x= np.array([0,1,2,3,4,3,2,1])
X= fp.fft(x)
X

array([16.   -0.j, -6.828+0.j,  0.   -0.j, -1.172+0.j,  0.   -0.j,
       -1.172-0.j,  0.   +0.j, -6.828-0.j])

In [120]:
N= x.size
M= N//2
Xc= fp.dct(x[0:M+1], type=1)
Xc

array([16.   , -6.828,  0.   , -1.172,  0.   ])