In [1]:
import numpy as np
import scipy.linalg as lg
import scipy.fftpack as fp

np.set_printoptions(precision=3, suppress=True)
π= np.pi
π

3.141592653589793

In [2]:
x= np.array([1,0,0,0,0,0,0,0])
X= fp.fft(x)
xx= fp.ifft(X)
x, X, xx

(array([1, 0, 0, 0, 0, 0, 0, 0]),
 array([1.-0.j, 1.+0.j, 1.-0.j, 1.+0.j, 1.-0.j, 1.-0.j, 1.+0.j, 1.-0.j]),
 array([1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.-0.j, 0.+0.j]))

In [3]:
N= 4
n= np.arange(N).reshape(-1,1)# rows= N, cols=1
k= np.arange(N).reshape(1,-1)# 1 x N
dftMat= np.exp(-1j*2*π/N*n@k)
dftMat

array([[ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j],
       [ 1.+0.j,  0.-1.j, -1.-0.j, -0.+1.j],
       [ 1.+0.j, -1.-0.j,  1.+0.j, -1.-0.j],
       [ 1.+0.j, -0.+1.j, -1.-0.j,  0.-1.j]])

In [4]:
X= x@dftMat  # x.shape= (1,N); dftMat.shape==(N,N)
X # X.shape= (N,N)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 8)

In [ ]:
M= np.array([[1,2],
             [3,4]])
L= np.array([[1,-2],
             [-3,5]])

Q= M + 1j*L
Q@lg.inv(Q)

In [ ]:
np.isclose(np.eye(2), M@L*(1/(-2)))

In [ ]:
M= np.random.random((2,2))
M

In [ ]:
lg.det(M)

In [ ]:
lg.inv(M)*lg.det(M)

In [ ]:
M.transpose()

In [ ]:
z= 10+20j

In [ ]:
z.conjugate()

In [ ]:
dftMat

In [ ]:
%timeit idftMat= lg.inv(dftMat)
# 115 # very slow

In [ ]:
%timeit idftMat= dftMat.transpose().conjugate()
# 2.7 # fast

In [ ]:
115/2.7

In [ ]:
%timeit dftMat.transpose().conjugate() /N # is Fast

In [ ]:
%timeit lg.inv(dftMat) # is slow

In [ ]:
xx= X@idftMat
xx

In [ ]:
idftMat2= dftMat.T.conj() /N
idftMat2

In [ ]:
xx2= X@idftMat2
xx2

In [ ]:
np.isclose(idftMat, idftMat2)

In [ ]:
dftMat.conj().transpose()/N \
@ dftMat

In [ ]:
np.eye(4)

In [ ]:
dftMat[1,:].conj() @ dftMat[:,3].T

In [ ]:
N=4
W= np.random.random([N,N]) + 1j* np.random.random([N,N]) 
W

In [ ]:
iW= lg.inv(W)
iW

In [ ]:
W@iW

In [ ]:

N=1024
W= np.random.random([N,N]) + 1j* np.random.random([N,N]) 
%timeit iW= lg.inv(W)
#W, iW, W@iW #, np.allclose(W@iW, np.eye(N))

In [ ]:

N=1024
W= np.random.random([N,N]) + 1j* np.random.random([N,N]) 
%timeit tW= W.T.conj()

In [ ]:
N= 1024
x= np.random.random(N)

def ryDft(x):
    n= np.arange(N).reshape(-1,1)
    k= np.arange(N).reshape(1,-1)
    
    dftMat= np.exp(-1j*2*π/N*n@k)
    
    X= x @ dftMat
    
    return X

def ryDft(x):
    n= np.arange(N).reshape(-1,1)
    k= np.arange(N).reshape(1,-1)
    
    dftMat= np.exp(-1j*2*π/N*n@k)
    
    X= x @ dftMat
    
    return X

In [ ]:
## %timeit X= ryDft(x)

n= np.arange(N).reshape(-1,1)
k= np.arange(N).reshape(1,-1)

dftMat= np.exp(-1j*2*π/N*n@k)

%timeit X= x @ dftMat
# 880 µs 

In [ ]:
%timeit X1= fp.fft(x)

In [ ]:
858 /22.6, (N*N) / (N*np.log(N))

In [ ]:
idftMat = dftMat.T.conj()/N

In [5]:
%timeit dftMat_inv= lg.inv(dftMat)
# 91.4 ms ± 4.55 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

10.7 µs ± 77.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [6]:
%timeit dftMat_transconj= dftMat.T.conj()
# 5.93 ms ± 31.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


718 ns ± 4.82 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [7]:
91.4/5.93 # == 15.41
# when N=1024, .inv() / .T.conj() = 15 times slower

15.413153456998316

In [8]:
# DFT (N-point)
# DCT- type1 (M+1) point
# where M= N/2
# and input to DFT is appended to be even-symmetric
# x8points= [1,2,3,4,5,4,3,2]
# x5points= [1,2,3,4,5]
# DCT(x5points)[k] == DFT(x8points)[k], for k in [0,1,2,3,4]

x8points= np.array([1,2,3,4,5,4,3,2])
x5points= np.array([1,2,3,4,5])

fp.fft(x8points), fp.dct(x5points, type=1)

(array([24.   -0.j, -6.828+0.j,  0.   -0.j, -1.172+0.j,  0.   -0.j,
        -1.172-0.j,  0.   +0.j, -6.828-0.j]),
 array([24.   , -6.828,  0.   , -1.172,  0.   ]))

In [9]:
# cosMat vs dftMat
N=8
n= np.arange(N).reshape(-1,1)
k= np.arange(N).reshape(1,-1)
dftMat= np.exp(-1j*2*π/N*n@k)
dftMat

array([[ 1.   +0.j   ,  1.   +0.j   ,  1.   +0.j   ,  1.   +0.j   ,
         1.   +0.j   ,  1.   +0.j   ,  1.   +0.j   ,  1.   +0.j   ],
       [ 1.   +0.j   ,  0.707-0.707j,  0.   -1.j   , -0.707-0.707j,
        -1.   -0.j   , -0.707+0.707j, -0.   +1.j   ,  0.707+0.707j],
       [ 1.   +0.j   ,  0.   -1.j   , -1.   -0.j   , -0.   +1.j   ,
         1.   +0.j   ,  0.   -1.j   , -1.   -0.j   , -0.   +1.j   ],
       [ 1.   +0.j   , -0.707-0.707j, -0.   +1.j   ,  0.707-0.707j,
        -1.   -0.j   ,  0.707+0.707j,  0.   -1.j   , -0.707+0.707j],
       [ 1.   +0.j   , -1.   -0.j   ,  1.   +0.j   , -1.   -0.j   ,
         1.   +0.j   , -1.   -0.j   ,  1.   +0.j   , -1.   -0.j   ],
       [ 1.   +0.j   , -0.707+0.707j,  0.   -1.j   ,  0.707+0.707j,
        -1.   -0.j   ,  0.707-0.707j, -0.   +1.j   , -0.707-0.707j],
       [ 1.   +0.j   , -0.   +1.j   , -1.   -0.j   ,  0.   -1.j   ,
         1.   +0.j   , -0.   +1.j   , -1.   -0.j   , -0.   -1.j   ],
       [ 1.   +0.j   ,  0.707+0.707j, -0.

In [10]:
M=N//2

n= np.arange(M+1).reshape(-1,1)
k= np.arange(M+1).reshape(1,-1)

cosMat1= np.cos(π/M*n@k)
cosMat1.T @ cosMat1

array([[ 5.,  0.,  1.,  0.,  1.],
       [ 0.,  3.,  0.,  1., -0.],
       [ 1.,  0.,  3.,  0.,  1.],
       [ 0.,  1.,  0.,  3., -0.],
       [ 1., -0.,  1., -0.,  5.]])

In [11]:
cosMat4= np.cos(π/(M+1)*(n+1/2)@(k+1/2))
cosMat4.T @ cosMat4

array([[ 2.5,  0. ,  0. , -0. , -0. ],
       [ 0. ,  2.5, -0. ,  0. ,  0. ],
       [ 0. , -0. ,  2.5, -0. , -0. ],
       [-0. ,  0. , -0. ,  2.5, -0. ],
       [-0. ,  0. , -0. , -0. ,  2.5]])

In [12]:
cosMat2= np.cos(π/(M+1)*(n+1/2)@(k))
cosMat2.T @ cosMat2

array([[ 5. ,  0. , -0. ,  0. , -0. ],
       [ 0. ,  2.5,  0. , -0. ,  0. ],
       [-0. ,  0. ,  2.5,  0. , -0. ],
       [ 0. , -0. ,  0. ,  2.5,  0. ],
       [-0. ,  0. , -0. ,  0. ,  2.5]])

In [13]:
cosMat3= np.cos(π/(M+1)*(n)@(k+1/2))
cosMat3.T @ cosMat3

array([[3. , 0.5, 0.5, 0.5, 0.5],
       [0.5, 3. , 0.5, 0.5, 0.5],
       [0.5, 0.5, 3. , 0.5, 0.5],
       [0.5, 0.5, 0.5, 3. , 0.5],
       [0.5, 0.5, 0.5, 0.5, 3. ]])

In [14]:
fp.rfft?

In [15]:
x= np.array([1,2,3,4,5,4,3,2])
fp.fft(x), \
fp.rfft(x),\
fp.dct(x[0:4+1], type=1)

(array([24.   -0.j, -6.828+0.j,  0.   -0.j, -1.172+0.j,  0.   -0.j,
        -1.172-0.j,  0.   +0.j, -6.828-0.j]),
 array([24.   , -6.828,  0.   ,  0.   , -0.   , -1.172,  0.   ,  0.   ]),
 array([24.   , -6.828,  0.   , -1.172,  0.   ]))

In [16]:
N=1024
x= np.random.random(N)

In [17]:
%timeit X_fft= fp.fft(x)

11.4 µs ± 113 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [18]:
%timeit X_rfft= fp.rfft(x)

8.67 µs ± 284 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [19]:
%timeit X_dct1= fp.dct(x[0:N//2+1], type=1)

9.95 µs ± 40 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [20]:
import numpy as np
import scipy.fftpack as fp

N= 1024
x= np.random.random(N) #np.ones(N)

In [21]:
X= fp.fft(x)
X

array([500.629 -0.j   ,   5.054+18.258j,   9.091 +5.081j, ...,
        -6.814-18.179j,   9.091 -5.081j,   5.054-18.258j])

In [22]:
π= np.pi

n= np.arange(N)
k= np.arange(N)

W= np.exp(np.outer(n,k) * (-1j*2*π/N))

In [23]:
X= x@W
X

array([500.629 +0.j   ,   5.054+18.258j,   9.091 +5.081j, ...,
        -6.814-18.179j,   9.091 -5.081j,   5.054-18.258j])

In [24]:
import numpy as np

π= np.pi

def ryFFT(x):
    
    N= x.size
    if N == 1:
        X= x
        return X
    
    He = ryFFT(x[0::2])
    Ho = ryFFT(x[1::2])
    
    k= np.arange(N)
    w= np.exp(-1j*2*π/N)
    
    X=   np.tile(He, 2)       \
       + np.tile(Ho, 2) * w**k
    
    return X

ryFFT(x)

array([500.629 +0.j   ,   5.054+18.258j,   9.091 +5.081j, ...,
        -6.814-18.179j,   9.091 -5.081j,   5.054-18.258j])

In [25]:
%timeit X= fp.fft(x)
# 11.2 µs ± 54.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

11.4 µs ± 47.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [26]:
%timeit X1= x@W
# 329 µs ± 10.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

296 µs ± 11.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [27]:
%timeit X2= ryFFT(x) 
# 14 ms ± 47.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

# 有關於速度，我們自己的 implementation 基本上還是很難與系統抗衡！！應該與 memory 的存取有關！

18.2 ms ± 112 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [28]:
# fp.fft : x@W : ryFFT
11.2, 329, 14000
1, 329/11.2, 14000/11.2

(1, 29.375000000000004, 1250.0)

In [34]:
x= np.array([0,1,2,3,4,3,2,1])
X= fp.fft(x)
X

array([16.   -0.j, -6.828+0.j,  0.   -0.j, -1.172+0.j,  0.   -0.j,
       -1.172-0.j,  0.   +0.j, -6.828-0.j])

In [32]:
N= x.size
M= N//2
Xc= fp.dct(x[0:M+1], type=1)
Xc

array([16.   , -6.828,  0.   , -1.172,  0.   ])