In [1]:
import numpy as np
import matplotlib.pyplot as pl
import pandas as pd
import scipy.signal as sg


In [2]:
np.convolve?

$
(a * v)[n] = \sum_{m = -\infty}^{\infty} a[m] v[n - m]
$

In [ ]:
a= np.array([1,2,3,4,5,6,7,8,9,10])

v= np.array([1,1,1,1])

np.convolve(a,v,mode='valid'),\
np.convolve(a,v,mode='same'),\
np.convolve(a,v,mode='full')

(array([10, 14, 18, 22, 26, 30, 34]),
 array([ 3,  6, 10, 14, 18, 22, 26, 30, 34, 27]),
 array([ 1,  3,  6, 10, 14, 18, 22, 26, 30, 34, 27, 19, 10]))

In [11]:
w= np.array([1,-1,1,-1])
np.convolve(a,w,mode='valid'),\
np.convolve(a,w,mode='same'),\
np.convolve(a,w,mode='full')


(array([2, 2, 2, 2, 2, 2, 2]),
 array([ 1,  2,  2,  2,  2,  2,  2,  2,  2, -9]),
 array([  1,   1,   2,   2,   2,   2,   2,   2,   2,   2,  -9,   1, -10]))

In [33]:
M= a.size
N= v.size

aa= np.concatenate((a,np.zeros(N-1)))
vv= np.concatenate((v,np.zeros(M-1)))

M= aa.size
N= vv.size

m= np.arange(M).reshape(1,-1)
n= np.arange(N).reshape(-1,1)


(aa[m]*vv[n-m]).sum(axis=1)

array([ 1.,  3.,  6., 10., 14., 18., 22., 26., 30., 34., 27., 19., 10.])

In [34]:
m, n

(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]), array([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12]]))

In [44]:
m-n

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12],
       [ -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [ -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8],
       [ -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7],
       [ -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6],
       [ -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5],
       [ -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4],
       [ -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3],
       [-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2],
       [-11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1],
       [-12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0]])

In [45]:
n-m

array([[  0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10, -11, -12],
       [  1,   0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10, -11],
       [  2,   1,   0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10],
       [  3,   2,   1,   0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9],
       [  4,   3,   2,   1,   0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8],
       [  5,   4,   3,   2,   1,   0,  -1,  -2,  -3,  -4,  -5,  -6,  -7],
       [  6,   5,   4,   3,   2,   1,   0,  -1,  -2,  -3,  -4,  -5,  -6],
       [  7,   6,   5,   4,   3,   2,   1,   0,  -1,  -2,  -3,  -4,  -5],
       [  8,   7,   6,   5,   4,   3,   2,   1,   0,  -1,  -2,  -3,  -4],
       [  9,   8,   7,   6,   5,   4,   3,   2,   1,   0,  -1,  -2,  -3],
       [ 10,   9,   8,   7,   6,   5,   4,   3,   2,   1,   0,  -1,  -2],
       [ 11,  10,   9,   8,   7,   6,   5,   4,   3,   2,   1,   0,  -1],
       [ 12,  11,  10,   9,   8,   7,   6,   5,   4,   3,   2,   1,   0]])

In [52]:
import sympy as sy
x,y,z= sy.symbols('x,y,z')


In [48]:
sy.symbols?

In [54]:
a= sy.symbols('a:10')
b= sy.symbols('b:10')
a,b

((a0, a1, a2, a3, a4, a5, a6, a7, a8, a9),
 (b0, b1, b2, b3, b4, b5, b6, b7, b8, b9))

In [105]:
f= sum([a[i]*x**i for i in range(3)]) 
g= sum([b[i]*x**i for i in range(3)])
(f*g).expand().collect(x)

a0*b0 + a2*b2*x**4 + x**3*(a1*b2 + a2*b1) + x**2*(a0*b2 + a1*b1 + a2*b0) + x*(a0*b1 + a1*b0)

In [107]:
(f**2).expand().collect(x)

a0**2 + 2*a0*a1*x + 2*a1*a2*x**3 + a2**2*x**4 + x**2*(2*a0*a2 + a1**2)

In [108]:
(f**3).expand().collect(x)

a0**3 + 3*a0**2*a1*x + 3*a1*a2**2*x**5 + a2**3*x**6 + x**4*(3*a0*a2**2 + 3*a1**2*a2) + x**3*(6*a0*a1*a2 + a1**3) + x**2*(3*a0**2*a2 + 3*a0*a1**2)